### PR TITLE
Hopper integration for LBA items

### PR DESCRIPTION
**Pull request by shartte**

### CODE REVIEW

**Comment by AlexIIL** [comment]
Just to check: are you ok licensing all of these files under `MPLv2`? (as you haven't added the license header https://github.com/AlexIIL/LibBlockAttributes/blob/0.7.x-1.16.x/misc/LICENSE_HEADER.txt)

**Comment by shartte** [comment]
Oh! Absolutly, I'd even put them under public domain if that mattered. Should I add these headers?

**Comment by AlexIIL** [comment]
Yes please - just running `gradle updateLicense` should add them automatically

**Comment by shartte** [comment]
Done.

**Comment by AlexIIL** [comment]
Thanks!

**Pull request merged**
