### PR TITLE
Fix fallbacks

### PR DESCRIPTION
**Pull request by Technici4n**
LBA tries to skip running fallback adders a bit too aggressively, this should fix it.

### CODE REVIEW

**Comment by AlexIIL** [comment]
This won't work properly because `CompatLeveledMap..getEntry` only returns the *first* such entry for performance. (Changing this would defeat the point of using a map at all, since later ones added for a given key replace earlier ones). Also, the ones you're changing aren't fallback adders - instead those are the "per-block/item specific adders", which are expected to be accurate.

What bug does this fix?

**Comment by Technici4n** [comment]
Some mod is making `Block` implement `InventoryProvider` (probably universal components, which is dead, but yeah...). This means that generic fallback adders don't get a chance to run, but I need them to work for compat with MI.

**Comment by AlexIIL** [comment]
...oh.

**Comment by AlexIIL** [comment]
In which case the "fix" might be to remove <https://github.com/AlexIIL/LibBlockAttributes/blob/0.8.x-1.16.x/src/main/java/alexiil/mc/lib/attributes/CompatLeveledMap.java#L246-L266>, but that will obviously break UC :/

**Comment by Technici4n** [comment]
Yeah, I don't know what the best solution is... :(

**Comment by AlexIIL** [comment]
Can you link to your MI compat? If all of the MI blocks extend a common block then you could register MI compat based on that?

**Comment by Technici4n** [comment]
https://github.com/AztechMC/Modern-Industrialization/blob/master/src/main/java/aztech/modern_industrialization/transferapi/impl/compat/TransferLbaCompat.java

I could register my blocks, but generic compat code will be needed once the transfer API is merged (if it is ever merged :P).

**Comment by AlexIIL** [comment]
Oh, right.

**Comment by Technici4n** [comment]
The easiest solution might be to blacklist UC, I don't think anyone is using it anyway.

**Comment by AlexIIL** [comment]
Sadly, yeah. How did you find this bug though? In theory UC must have been installed when some-one encounted it?

**Comment by Technici4n** [comment]
I was testing on a test server known as FiberCraft and noticed that every MI pipe disconnected from MI machines. :P

**Comment by Technici4n** [comment]
The pack is a bit old, I think inmis (a backpack mod) used to have UC, but we got it removed because it was causing performance issues. FiberCraft probably still has an old version of it.

**Comment by Technici4n** [comment]
I could probably remove it from the pack, but I'm not comfortable releasing a build of my mod knowing that all inventories could become invisible when another mod is installed.

**Comment by AlexIIL** [comment]
Yeah that's fair enough. I'd be happy to remove the UC compat code from LBA then (alongside a suitable warning message in the changelog). I think that's better than blacklisting UC directly. Alternatively we could see if there's a better way for UC to implement it's compat, or contact Boundarybreaker to see if she has a better idea?

**Comment by Technici4n** [comment]
Possibly, but I am pretty sure everyone is either using `(Sided)Inventory` or LBA directly at the moment. If I recall correctly, AOF3 doesn't have UC (only inmis used to require it for its backpack items).

**Comment by AlexIIL** [comment]
Fair enough.

**Comment by AlexIIL** [comment]
Okay, I've pushed [0.8.9-pre.2](https://alexiil.uk/maven/alexiil/mc/lib/libblockattributes-all/0.8.9-pre.2/) which removes the UC compatibility code, and now crashes if both are installed (via `breaks`)

**Comment by AlexIIL** [comment]
(As such this PR is not going to be merged, but that should be a sufficient workaround?)

**Comment by Technici4n** [comment]
That should be fine, many thanks!

**Pull request closed without merging**
