### PR TITLE
Make Placing Fluids Easier

### PR DESCRIPTION
**Pull request by shartte**
I did not test this properly yet. But before I bury this in my mod, I thought: "Why not share this" :-D

The idea is to enhance `FluidWorldUtil` to have an easy way of placing fluids in the world. At least the ones that suport it (vanilla Water, Lava for example).
Also: when SIMULATE is used, can I still use `split`? It'd modify the originally passed in volume...

### CODE REVIEW

**Comment by AlexIIL** [comment]
Looks good, thanks!

To be honest I'd rather you didn't change quite so many imports around, but that's quite minor so I'll re-organise them after merging.

> Also: when SIMULATE is used, can I still use split? It'd modify the originally passed in volume...

As all of LBA's fluid methods do not modify the passed FluidVolume I'd rather not change that for this. However you can still copy() and then split 1 bucket of the volume off rather than subtracting directly.

**Comment by shartte** [comment]
Oh sorry about the import ordering, that was probably an unintentional IntelliJ auto-format :-|

**Comment by AlexIIL** [comment]
Ah ok - I'll have to copy over buildcraft's import order as it should be possible to import it.

**Comment by AlexIIL** [comment]
Ok, I've pushed this in 0.7.1-pre.1 to the BC maven. (As a pre-release rather than a full release because I was quite close to pushing a lot of other stuff too).

If you find any bugs with this please PR fixes though :)

**Comment by shartte** [comment]
Will do, I had also copy pasted this into the Fluid Formation Planes.
Once I get to testing these, I'll amend fixes to this code as needed.

**Pull request merged**
