### PR TITLE
Initial port to 1.16.2 and newer Fabric/loom version

### PR DESCRIPTION
**Pull request by shartte**
This is WIP in the sense that it most likely contains changes you don't want, and you'd also have to clarify how to handle versioning of this since it is such a breaking change.

### CODE REVIEW

**Comment by AlexIIL** [comment]
Thanks! I'll merge this manually as I'm going to break water a bit more than you are - although I will copy over the config changes as those seem reasonable as-is.

**Comment by AlexIIL** [comment]
I've pushed my work so far to https://github.com/AlexIIL/LibBlockAttributes/tree/0.8.x-1.16.x - although I haven't fully finished testing it yet.

**Comment by shartte** [comment]
@AlexIIL Have you pushed a pre-version of that branch so I can try this out via Maven?

**Comment by AlexIIL** [comment]
In theory the only difference between this and release will be the changelog, but in case it's not: https://mod-buildcraft.com/maven/alexiil/mc/lib/libblockattributes-all/0.8.0-pre.18/

**Comment by AlexIIL** [comment]
(Merged manually in https://github.com/AlexIIL/LibBlockAttributes/commit/9f4e573c2b72ebaf6ee47085075489c46af356fb)

**Pull request closed without merging**
